### ISSUE TITLE
Docker build faliure issues

### ISSUE THREAD

**Issue by djKooks** [AGLEnergy/arc#5]
Hello.
I'm trying to build docker images with local files, but faced an issue.
When trying to build docker image:
```
$ docker build -t arc-test .
...
Step 13/16 : RUN chmod +x /opt/tutorial/nyctaxi/download_raw_data_large.sh
 ---> Using cache
 ---> 6582377a36a9
Step 14/16 : COPY log4j.properties /opt/spark/conf/log4j.properties
 ---> Using cache
 ---> 7b54a18ff81f
Step 15/16 : COPY target/scala-2.11/arc.jar /opt/spark/jars/arc.jar
COPY failed: stat /var/lib/docker/tmp/docker-builder127530358/target/scala-2.11/arc.jar: no such file or directory
```
I run `sbt assembly` first, but couldn't find `target/scala-2.11/arc.jar` file.
Actually, `sbt assembly` shows test failure, but it seems not the reason.
```
...
[info] - Type String Column
[info] Run completed in 4 minutes, 15 seconds.
[info] Total number of tests run: 134
[info] Suites: completed 35, aborted 0
[info] Tests: succeeded 133, failed 1, canceled 0, ignored 0, pending 0
[info] *** 1 TEST FAILED ***
[error] Failed tests:
[error]         au.com.agl.arc.JSONLoadSuite
[error] (test:test) sbt.TestsFailedException: Tests unsuccessful
[error] Total time: 264 s, completed Aug 7, 2018 2:42:30 PM
```
Do you know about it?

**Comment by seddonm1** [comment]
the docker issue is caused by the tests failing in the `sbt assembly` command. can you please run `sbt test` and print out the message for the failed test in JSONLoadSuite?

**Comment by djKooks** [comment]
@seddonm1 
```
...
[info] JSONLoadSuite:
[info] - JSONLoad *** FAILED ***
[info]   org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 1.0 failed 1 times, most recent failure: Lost task 0.0 in stage 1.0 (TID 2, localhost, executor driver): java.lang.IllegalArgumentException: Error while instantiating 'org.apache.spark.sql.internal.SessionStateBuilder':
[info] 	at org.apache.spark.sql.SparkSession$.org$apache$spark$sql$SparkSession$$instantiateSessionState(SparkSession.scala:1068)
[info] 	at org.apache.spark.sql.SparkSession$$anonfun$sessionState$2.apply(SparkSession.scala:144)
[info] 	at org.apache.spark.sql.SparkSession$$anonfun$sessionState$2.apply(SparkSession.scala:143)
[info] 	at scala.Option.getOrElse(Option.scala:121)
[info] 	at org.apache.spark.sql.SparkSession.sessionState$lzycompute(SparkSession.scala:143)
[info] 	at org.apache.spark.sql.SparkSession.sessionState(SparkSession.scala:140)
[info] 	at org.apache.spark.sql.SparkSession$$anonfun$1$$anonfun$apply$1.apply(SparkSession.scala:95)
[info] 	at org.apache.spark.sql.SparkSession$$anonfun$1$$anonfun$apply$1.apply(SparkSession.scala:95)
[info] 	at scala.Option.map(Option.scala:146)
[info] 	at org.apache.spark.sql.SparkSession$$anonfun$1.apply(SparkSession.scala:95)
[info] 	at org.apache.spark.sql.SparkSession$$anonfun$1.apply(SparkSession.scala:94)
[info] 	at org.apache.spark.sql.internal.SQLConf$.get(SQLConf.scala:110)
[info] 	at org.apache.spark.sql.types.DataType.sameType(DataType.scala:84)
[info] 	at org.apache.spark.sql.catalyst.analysis.TypeCoercion$$anonfun$1.apply(TypeCoercion.scala:105)
[info] 	at org.apache.spark.sql.catalyst.analysis.TypeCoercion$$anonfun$1.apply(TypeCoercion.scala:86)
[info] 	at org.apache.spark.sql.execution.datasources.json.JsonInferSchema$.compatibleType(JsonInferSchema.scala:271)
[info] 	at org.apache.spark.sql.execution.datasources.json.JsonInferSchema$$anonfun$org$apache$spark$sql$execution$datasources$json$JsonInferSchema$$compatibleRootType$1.apply(JsonInferSchema.scala:262)
[info] 	at org.apache.spark.sql.execution.datasources.json.JsonInferSchema$$anonfun$org$apache$spark$sql$execution$datasources$json$JsonInferSchema$$compatibleRootType$1.apply(JsonInferSchema.scala:246)
[info] 	at scala.collection.TraversableOnce$$anonfun$foldLeft$1.apply(TraversableOnce.scala:157)
[info] 	at scala.collection.TraversableOnce$$anonfun$foldLeft$1.apply(TraversableOnce.scala:157)
[info] 	at scala.collection.Iterator$class.foreach(Iterator.scala:893)
[info] 	at scala.collection.AbstractIterator.foreach(Iterator.scala:1336)
[info] 	at scala.collection.TraversableOnce$class.foldLeft(TraversableOnce.scala:157)
[info] 	at scala.collection.AbstractIterator.foldLeft(Iterator.scala:1336)
[info] 	at scala.collection.TraversableOnce$class.fold(TraversableOnce.scala:212)
[info] 	at scala.collection.AbstractIterator.fold(Iterator.scala:1336)
[info] 	at org.apache.spark.rdd.RDD$$anonfun$fold$1$$anonfun$19.apply(RDD.scala:1090)
[info] 	at org.apache.spark.rdd.RDD$$anonfun$fold$1$$anonfun$19.apply(RDD.scala:1090)
[info] 	at org.apache.spark.SparkContext$$anonfun$33.apply(SparkContext.scala:2130)
[info] 	at org.apache.spark.SparkContext$$anonfun$33.apply(SparkContext.scala:2130)
[info] 	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87)
[info] 	at org.apache.spark.scheduler.Task.run(Task.scala:109)
[info] 	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:345)
[info] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[info] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[info] 	at java.lang.Thread.run(Thread.java:748)
[info] Caused by: java.lang.IllegalStateException: LiveListenerBus is stopped.
[info] 	at org.apache.spark.scheduler.LiveListenerBus.addToQueue(LiveListenerBus.scala:97)
[info] 	at org.apache.spark.scheduler.LiveListenerBus.addToStatusQueue(LiveListenerBus.scala:80)
[info] 	at org.apache.spark.sql.internal.SharedState.<init>(SharedState.scala:93)
[info] 	at org.apache.spark.sql.SparkSession$$anonfun$sharedState$1.apply(SparkSession.scala:120)
[info] 	at org.apache.spark.sql.SparkSession$$anonfun$sharedState$1.apply(SparkSession.scala:120)
[info] 	at scala.Option.getOrElse(Option.scala:121)
[info] 	at org.apache.spark.sql.SparkSession.sharedState$lzycompute(SparkSession.scala:120)
[info] 	at org.apache.spark.sql.SparkSession.sharedState(SparkSession.scala:119)
[info] 	at org.apache.spark.sql.internal.BaseSessionStateBuilder.build(BaseSessionStateBuilder.scala:286)
[info] 	at org.apache.spark.sql.SparkSession$.org$apache$spark$sql$SparkSession$$instantiateSessionState(SparkSession.scala:1065)
[info] 	... 35 more
[info]
[info] Driver stacktrace:
[info]   at org.apache.spark.scheduler.DAGScheduler.org$apache$spark$scheduler$DAGScheduler$$failJobAndIndependentStages(DAGScheduler.scala:1602)
[info]   at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1590)
[info]   at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1589)
[info]   at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
[info]   at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
[info]   at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:1589)
[info]   at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:831)
[info]   at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:831)
[info]   at scala.Option.foreach(Option.scala:257)
[info]   at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:831)
[info]   ...
[info]   Cause: java.lang.IllegalArgumentException: Error while instantiating 'org.apache.spark.sql.internal.SessionStateBuilder':
[info]   at org.apache.spark.sql.SparkSession$.org$apache$spark$sql$SparkSession$$instantiateSessionState(SparkSession.scala:1068)
[info]   at org.apache.spark.sql.SparkSession$$anonfun$sessionState$2.apply(SparkSession.scala:144)
[info]   at org.apache.spark.sql.SparkSession$$anonfun$sessionState$2.apply(SparkSession.scala:143)
[info]   at scala.Option.getOrElse(Option.scala:121)
[info]   at org.apache.spark.sql.SparkSession.sessionState$lzycompute(SparkSession.scala:143)
[info]   at org.apache.spark.sql.SparkSession.sessionState(SparkSession.scala:140)
[info]   at org.apache.spark.sql.SparkSession$$anonfun$1$$anonfun$apply$1.apply(SparkSession.scala:95)
[info]   at org.apache.spark.sql.SparkSession$$anonfun$1$$anonfun$apply$1.apply(SparkSession.scala:95)
[info]   at scala.Option.map(Option.scala:146)
[info]   at org.apache.spark.sql.SparkSession$$anonfun$1.apply(SparkSession.scala:95)
[info]   ...
[info]   Cause: java.lang.IllegalStateException: LiveListenerBus is stopped.
[info]   at org.apache.spark.scheduler.LiveListenerBus.addToQueue(LiveListenerBus.scala:97)
[info]   at org.apache.spark.scheduler.LiveListenerBus.addToStatusQueue(LiveListenerBus.scala:80)
[info]   at org.apache.spark.sql.internal.SharedState.<init>(SharedState.scala:93)
[info]   at org.apache.spark.sql.SparkSession$$anonfun$sharedState$1.apply(SparkSession.scala:120)
[info]   at org.apache.spark.sql.SparkSession$$anonfun$sharedState$1.apply(SparkSession.scala:120)
[info]   at scala.Option.getOrElse(Option.scala:121)
[info]   at org.apache.spark.sql.SparkSession.sharedState$lzycompute(SparkSession.scala:120)
[info]   at org.apache.spark.sql.SparkSession.sharedState(SparkSession.scala:119)
[info]   at org.apache.spark.sql.internal.BaseSessionStateBuilder.build(BaseSessionStateBuilder.scala:286)
[info]   at org.apache.spark.sql.SparkSession$.org$apache$spark$sql$SparkSession$$instantiateSessionState(SparkSession.scala:1065)
...
```
It looks like problem of Spark setting. Can you find something?

**Comment by seddonm1** [comment]
can you please try:

```
sbt test-only *JSONLoad*
```

Also can you confirm you are compiling with JVM 8.x?

**Comment by seddonm1** [comment]
This is likely just due to your build environment. I have just pushed a change to allow you to build inside a predictable docker container - see within this section: https://github.com/AGLEnergy/arc#library

**Comment by djKooks** [comment]
@seddonm1 now build works well. Thanks!
